### ISSUE TITLE
Setup Isaac's Dev Environment for Computer Combat

### ISSUE THREAD

**Issue by janfic** [janfic/computercombat#131]
Can't work on stuff if nothing works
- [x] Gradle Setup
- [x] Successful Compilation and Run
  - [x] Desktop
  - [x] Local Server

**Comment by blakeearth** [comment]
I think I'm having JDK versioning issues. "Unsupported class file major version 60". Need to confirm version

**Comment by janfic** [comment]
**Current Versions Used**
Gradle: 6.3
JDK 14/15

**Common Gradle Commands**
`gradlew desktop:run` - runs main client
`gradlew server:run` - runs server locally
`gradlew desktop:build`
`gradlew tasks`
`gradlew clean`
NOTE:  `gradlew <task>` is used over `gradle <task>` to use the included wrapper. I get issues when not using `gradlew`

**Comment by blakeearth** [comment]
I have desktop and local server running. There is a crash when I try to log in. Is that expected?

**Comment by janfic** [comment]
Not expected but makes sense. I think the local server you run does not have permissions to AWS as it is by IP ( 99% sure )

**Comment by blakeearth** [comment]
Okay, that’s what I figured.
